### ISSUE TITLE
HACS installation is not working

### ISSUE THREAD

**Issue by thetic** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#9]
**Describe the bug**
Cannot add card to Lovelace

**To Reproduce**
1. Add custom repository to HACS with URL=*https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card* and Category=*Lovelace*
1. Install *Mail And Packages Custom Card* from *Front End* tab
1. Restart Home Assistant
1. Add *Manual* element to UI
1. Paste configuration from readme:
 ```yaml
type: 'custom:mail-and-packages-card'
name: Mail Summary
updated: sensor.mail_updated
details: true
image: false
```

**Expected behavior**
Element is added to Lovelace

**Screenshots or Error**
> Custom element doesn't exist: mail-and-packages-card.
> 
> `type: 'custom:mail-and-packages-card'`
> `name: Mail Summary`
> `updated: sensor.mail_updated`
> `details: true`
> `image: false`

**Hass environment:**
- Official Docker image version 0.114.0

**Desktop:**
 - OS: Arch Linux
 - Browser: Firefox 79.0

**Additional context**
- HACS version 1.3.3
